# fly.toml file for the Evapine project

app = "evapine"

# Define build settings
[build]
  dockerfile = "Dockerfile"  # Tells Fly.io to use the Dockerfile in your root directory for deployment.

# Configuration settings for environment variables
[env]
  PORT = "8080"  # Default port for Flask or other web apps running in the container.

# Define services to expose ports to the outside world
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

# Suggestions for Improvement or Considerations

# HTTPS (Optional)
# If you want your application to handle secure traffic (HTTPS), add an HTTPS handler
[[services.ports]]
  handlers = ["http", "tls"]
  port = 443

# Health Checks
# Useful to add health checks to ensure Fly.io can automatically determine if your app is running correctly
[services.health_checks]
  path = "/"
  interval = "10s"
  timeout = "2s"

# Volume (Optional)
# If your app needs persistent storage, you may want to add a volume
[mounts]
  source = "evapine_data"
  destination = "/data"
