# fly.toml file for the Evapine project

app = "evapine"

# Define build settings
[build]
  dockerfile = "Dockerfile"  # Tells Fly.io to use the Dockerfile in your root directory for deployment.

# Configuration settings for environment variables
[env]
  PORT = "8080"  # Default port for Flask or other web apps running in the container.

# Define services to expose ports to the outside world
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"  # Allow a brief startup time.
    interval = "15s"
    timeout = "2s"
    restart_limit = 0

# Optionally, you can add volumes configuration here if you need persistent storage:
# [mounts]
#   source = "my_volume"
#   destination = "/data"

